"use strict";

// Change 3 (docs/build-prompt-modes.md): missing and stale documents.
//
// "Generate what's missing. Regenerate only what's stale. Always show it
// before it takes effect. Never silently overwrite what the founder
// wrote." This module owns both halves; mode-switch.js calls
// checkMissingInput() on every mode entry, and commands/proto.js (or
// anything invoking a mode against its input) can call checkStale() the
// same way before proceeding.

const { PERSONAS, personaFor } = require("./personas");
const { readDoc, readInputDoc, writeDoc, generateDraft, runPersonaTurn, attachFullDocument, summarizeForThread } = require("./mode-docs");
const { recordGeneration, generationRecord, hashOf } = require("./doc-meta");
const { callFlash } = require("./llm");

const MODEL = "flash-fast";

// Which mode's persona produces a given document filename -- the mode to
// offer switching to / generating from when that document is missing.
function modeThatProduces(docFilename) {
	return Object.values(PERSONAS).find((p) => p.outputDoc === docFilename)?.mode || null;
}

// Returns null if the mode's input document exists (or the mode has no
// input requirement). Otherwise the shape needed to post Change 3's
// missing-document offer.
function checkMissingInput(id, mode) {
	const persona = personaFor(mode);
	if (!persona.inputDoc) return null;
	if (readInputDoc(id, mode)) return null;
	const missingMode = modeThatProduces(persona.inputDoc);
	const missingPersona = missingMode ? personaFor(missingMode) : null;
	return {
		mode,
		missingDoc: persona.inputDoc,
		missingMode,
		missingTitle: missingPersona?.outputTitle || persona.inputDoc,
		missingLabel: missingPersona?.label || null,
	};
}

function missingDocBlocks(id, offer) {
	const text =
		`${personaFor(offer.mode).label === "PM" ? "Product planning" : offer.mode[0].toUpperCase() + offer.mode.slice(1)} ` +
		`normally works from a ${offer.missingTitle.toLowerCase()}. There isn't one.\n` +
		`I can generate a draft from what exists so far, or you can switch to ${offer.missingMode} and write it yourself.`;
	return {
		text,
		blocks: [
			{ type: "section", text: { type: "mrkdwn", text } },
			{
				type: "actions",
				block_id: "missing_doc",
				elements: [
					{ type: "button", action_id: "generate_doc", style: "primary", text: { type: "plain_text", text: "Generate it" }, value: `${id}::${offer.missingMode}` },
					{ type: "button", action_id: `mode_switch_${offer.missingMode}`, text: { type: "plain_text", text: `Switch to ${offer.missingMode}` }, value: `${id}::${offer.missingMode}` },
				],
			},
		],
	};
}

// Runs the generate side of the offer: uses the persona for the MISSING
// document's own mode (not the mode the founder was trying to enter), so
// entering engineering with no product spec generates the product spec
// via the PM persona reading the research base, not an engineering
// shortcut. Writes the doc, records the generation snapshot (Change 3's
// staleness baseline), posts a summary + the full attachment.
async function generateMissingDoc({ id, mode, client, channel, threadTs, threadContext = "" }) {
	const inputBefore = readInputDoc(id, mode); // the missing mode's OWN input, e.g. research-kb.md for product
	const result = await generateDraft({ id, mode, threadContext });
	if (result.refusal) {
		await client.chat
			.postMessage({ channel, thread_ts: threadTs, text: `Couldn't generate a ${personaFor(mode).outputTitle}: ${result.refusal.what}\nUnblock: ${result.refusal.unblock}` })
			.catch(() => {});
		return { ok: false, reason: "refused", refusal: result.refusal };
	}
	writeDoc(id, mode, result.text, { autoGenerated: true });
	recordGeneration(id, mode, inputBefore);
	const summary = await summarizeForThread(result.text).catch(() => result.text.slice(0, 400));
	await client.chat
		.postMessage({ channel, thread_ts: threadTs, text: `⚙️ Auto-generated ${personaFor(mode).outputTitle} (${personaFor(mode).mode} mode):\n\n${summary}` })
		.catch(() => {});
	await attachFullDocument(client, { id, mode, channel, threadTs });
	return { ok: true, mode };
}

const CLASSIFY_PROMPT = [
	"You are comparing an OLD and a NEW version of an upstream document against a DOWNSTREAM document that was",
	"written based on the OLD version. For every substantive difference between OLD and NEW, classify it as one of:",
	"",
	"COSMETIC — wording only, no effect on anything the downstream document assumed or decided.",
	"ADDITIVE — a new requirement or fact that doesn't invalidate any existing downstream decision, just needs coverage.",
	"CONTRADICTORY — the downstream document rests on something that changed; a specific downstream decision no longer holds.",
	"",
	"Output one line per substantive difference, prefixed COSMETIC:, ADDITIVE:, or CONTRADICTORY:, describing the",
	"change and (for ADDITIVE/CONTRADICTORY) which part of the downstream document it affects. If there are no",
	"substantive differences at all, output exactly: NONE",
].join("\n");

function parseClassification(text) {
	const lines = String(text || "").split("\n").map((l) => l.trim()).filter(Boolean);
	const out = { cosmetic: [], additive: [], contradictory: [] };
	for (const line of lines) {
		const m = line.match(/^(COSMETIC|ADDITIVE|CONTRADICTORY):\s*(.*)$/i);
		if (!m) continue;
		out[m[1].toLowerCase()].push(m[2]);
	}
	return out;
}

// Compares the current input document against the snapshot it was last
// generated against. Returns null if there's no baseline to compare
// (never generated / tracked -- checkMissingInput owns "doesn't exist at
// all") or nothing changed. Otherwise the classified diff.
async function checkStale(id, mode) {
	const persona = personaFor(mode);
	if (!persona.inputDoc || !persona.outputDoc) return null;
	const current = readInputDoc(id, mode);
	const downstream = readDoc(id, mode);
	if (!current || !downstream) return null; // missing-doc case, not stale
	const rec = generationRecord(id, mode);
	if (!rec) return null; // no tracked baseline -- nothing to diff against
	if (hashOf(current) === rec.inputHash) return null; // unchanged

	const { content: text } = await callFlash(
		[
			{ role: "system", content: CLASSIFY_PROMPT },
			{
				role: "user",
				content: `--- DOWNSTREAM (${persona.outputTitle}) ---\n${downstream}\n\n--- OLD upstream ---\n${rec.inputSnapshot || "(none)"}\n\n--- NEW upstream ---\n${current}`,
			},
		],
		{ model: MODEL, maxTokens: 2048 },
	);
	if (/^NONE\s*$/i.test(text.trim())) return null;
	const classification = parseClassification(text);
	const isStale = classification.additive.length > 0 || classification.contradictory.length > 0;
	return { stale: isStale, classification, raw: text };
}

function staleDocBlocks(id, mode, report) {
	const persona = personaFor(mode);
	const counts = `${report.classification.contradictory.length} contradictory, ${report.classification.additive.length} additive, ${report.classification.cosmetic.length} cosmetic`;
	const text = `The upstream document changed since this ${persona.outputTitle.toLowerCase()} was written (${counts}).\nI can regenerate just the stale sections and show you the diff, or you can update them yourself.`;
	return {
		text,
		blocks: [
			{ type: "section", text: { type: "mrkdwn", text } },
			{
				type: "actions",
				block_id: "stale_doc",
				elements: [
					{ type: "button", action_id: "regenerate_stale", style: "primary", text: { type: "plain_text", text: "Regenerate stale sections" }, value: `${id}::${mode}` },
					{ type: "button", action_id: "stale_ack", text: { type: "plain_text", text: "I'll do it" }, value: `${id}::${mode}` },
				],
			},
		],
	};
}

// Section-scoped regeneration: the persona is given its own current
// document plus the classified changes and told to touch ONLY the
// sections those changes affect, copying everything else verbatim.
// Never a blind full rewrite -- "never silently overwrite what the
// founder wrote."
async function regenerateStaleSections({ id, mode, client, channel, threadTs }) {
	const persona = personaFor(mode);
	const report = await checkStale(id, mode);
	if (!report || !report.stale) return { ok: false, reason: "not_stale" };
	const current = readDoc(id, mode);
	const newInput = readInputDoc(id, mode);
	const affected = [...report.classification.contradictory, ...report.classification.additive].map((l) => `- ${l}`).join("\n");
	const messages = [
		{
			role: "system",
			content:
				`${persona.systemPrompt}\n\nYou previously wrote the ${persona.outputTitle} below. The upstream document changed. ` +
				"Revise ONLY the sections affected by the changes listed. Copy every other section byte-for-byte, unchanged -- " +
				"do not rephrase, do not reformat, do not touch anything not listed. Return the FULL document, revised sections " +
				"and all.",
		},
		{
			role: "user",
			content: `--- Current ${persona.outputTitle} ---\n${current}\n\n--- Changes to address ---\n${affected}\n\n--- New upstream document ---\n${newInput}`,
		},
	];
	const { content: revised } = await callFlash(messages, { model: MODEL, maxTokens: 8192 });
	writeDoc(id, mode, revised);
	recordGeneration(id, mode, newInput);
	if (client) {
		const summary = await summarizeForThread(revised).catch(() => revised.slice(0, 400));
		await client.chat.postMessage({ channel, thread_ts: threadTs, text: `♻️ Regenerated stale sections of the ${persona.outputTitle}:\n\n${summary}` }).catch(() => {});
		await attachFullDocument(client, { id, mode, channel, threadTs });
	}
	return { ok: true, before: current, after: revised, report };
}

// Writes the CURRENT MODE'S OWN document from the conversation so far.
//
// This was the hole: writeDoc was only ever reached by generateMissingDoc
// (the missing-input offer) and regenerateStaleSections (the stale
// offer), neither of which is on the conversational path. So a founder
// could work with the PM for an hour and `product-spec.md` would never
// exist -- and the spec would then be generated later, on switching to
// engineering, from the research KB alone as if that hour hadn't happened.
//
// Founder-triggered, never automatic, for the same reason profile diffs
// are proposed rather than applied (D-30): the document is the thing
// downstream modes feed on, so an unconsidered half-thought must not be
// able to overwrite a considered spec. Returns a preview the caller shows
// before it takes effect.
async function saveModeDocument({ id, mode, threadContext, client, channel, threadTs }) {
	const persona = personaFor(mode);
	if (!persona.outputDoc) {
		return { ok: false, reason: `${mode} mode produces no document (proto writes artifacts, audit writes a verdict)` };
	}
	const existing = readDoc(id, mode);
	const wc = (t) => String(t || "").split(/\s+/).filter(Boolean).length;

	// THE EXISTING DOCUMENT MUST BE IN THE PROMPT.
	//
	// It wasn't: runPersonaTurn loads a mode's INPUT document, never its
	// own, and brainstorm has no input at all -- so the save prompt told
	// the model to "carry forward anything still true" from a document it
	// could not see. Proven destructive: a save over a KB containing a
	// DGFT trade notice, three competitor names and unit economics wiped
	// all of them, because the model wrote a fresh document from the
	// conversation alone. Recoverable from git, but silently.
	const directive = existing
		? [
			`Below is the CURRENT ${persona.outputTitle}, followed by the conversation since.`,
			"",
			`--- CURRENT ${persona.outputTitle} ---`,
			existing,
			"--- end ---",
			"",
			`Rewrite it as one coherent ${persona.outputTitle} incorporating what the conversation settled.`,
			"This REPLACES the file, so everything still true must appear in your output -- specifics especially:",
			"numbers, named competitors, named regulations, prices, dates. Dropping a fact you were not asked to",
			"remove is the failure to avoid. Do not append a changelog; produce the document as it now stands.",
		].join("\n")
		: `Write the ${persona.outputTitle} from the conversation above, as a complete document.`;

	const result = await runPersonaTurn({ id, mode, threadContext, userText: directive, maxTokens: 8000 });
	if (result.refusal) return { ok: false, reason: "refused", refusal: result.refusal };

	// Never shrink a document silently. Change 3's rule is "always show it
	// before it takes effect; never silently overwrite what the founder
	// wrote" -- a large contraction is the signal that carry-forward
	// failed, and it is the one thing a founder cannot see from a summary.
	const before = wc(existing);
	const after = wc(result.text);
	const shrankBy = before ? Math.round(((before - after) / before) * 100) : 0;
	const materialShrink = before > 200 && shrankBy >= 40;

	writeDoc(id, mode, result.text);
	const summary = await summarizeForThread(result.text).catch(() => result.text.slice(0, 400));
	if (client && channel) {
		const verb = existing ? "Updated" : "Created";
		const delta = existing ? ` · ${before} → ${after} words` : ` · ${after} words`;
		const warn = materialShrink
			? `\n\n⚠️ *This shrank the document by ${shrankBy}%.* Check nothing was dropped — the previous version is in git history.`
			: "";
		await client.chat
			.postMessage({ channel, thread_ts: threadTs, text: `💾 ${verb} *${persona.outputTitle}* (\`${persona.outputDoc}\`)${delta}:\n\n${summary}${warn}` })
			.catch(() => {});
		await attachFullDocument(client, { id, mode, channel, threadTs });
	}
	return { ok: true, mode, created: !existing, wordCount: after, previousWordCount: before, shrankBy, materialShrink };
}

module.exports = {
	saveModeDocument,
	checkMissingInput,
	missingDocBlocks,
	generateMissingDoc,
	checkStale,
	staleDocBlocks,
	regenerateStaleSections,
	parseClassification,
};
