"use strict";

// Change 2 (docs/build-prompt-modes.md): document I/O for the mode
// chain, and "the feeding rule" -- a mode's persona sees the previous
// stage's document plus the live thread, nothing else. Change 1 wires
// this into the actual mode-switch flow in the bot; this module is the
// part that doesn't need the thread model to be correct on its own.

const fs = require("node:fs");
const path = require("node:path");
const { IDEAS_DIR } = require("./ideas");
const { PERSONAS, personaFor, parseRefusal } = require("./personas");
const { callFlash } = require("./llm");
const { uploadThreadFile } = require("./slack-files");

const MODEL = "flash-fast";

function docPath(id, mode) {
	const persona = personaFor(mode);
	if (!persona.outputDoc) return null;
	return path.join(IDEAS_DIR, id, persona.outputDoc);
}

function readDoc(id, mode) {
	const p = docPath(id, mode);
	if (!p || !fs.existsSync(p)) return null;
	return fs.readFileSync(p, "utf8");
}

// The feeding rule: the persona for `mode` reads *its own* input
// document (defined per-persona in personas.js, e.g. engineering reads
// product-spec.md) -- never anything further upstream, never a sibling
// mode's document. Returns null when there is nothing upstream yet
// (brainstorm, or a skipped stage -- Change 3 owns what happens then).
function readInputDoc(id, mode) {
	const persona = personaFor(mode);
	if (!persona.inputDoc) return null;
	const p = path.join(IDEAS_DIR, id, persona.inputDoc);
	if (!fs.existsSync(p)) return null;
	return fs.readFileSync(p, "utf8");
}

function writeDoc(id, mode, content, { autoGenerated = false } = {}) {
	const p = docPath(id, mode);
	if (!p) throw new Error(`mode-docs: mode "${mode}" produces no document`);
	fs.mkdirSync(path.dirname(p), { recursive: true });
	const body = autoGenerated
		? `> ⚙️ _Auto-generated — not written by a founder. Read before building on it._\n\n${content}`
		: content;
	fs.writeFileSync(p, body, "utf8");

	// COMMIT IT. Nothing in the document path did, so every mode document
	// a founder produced -- research KB, product spec, engineering spec,
	// deck -- lived only on the box. Found by noticing f05e's
	// product-spec.md sitting untracked after a real save: 1,038 words of
	// the founders' actual work product, outside the repo that D-21 calls
	// the system's only continuous memory and that D-38 makes the shared
	// substrate for all three of them. A box failure would have taken it,
	// and the other two founders could not read it.
	//
	// Fire-and-forget at the choke point rather than at each caller: a
	// commit must never block or fail a write (COMMANDS.md's failure
	// table), and putting it here covers callers that do not exist yet.
	// git.js excludes ideas/zz* so test scaffolds commit nothing.
	const rel = path.relative(path.join(IDEAS_DIR, ".."), p);
	require("./git")
		.commitAndPush([rel], `idea ${id}: ${mode} document updated`, (r) =>
			console.error(`mode-docs: could not commit ${rel}: ${r}`),
		)
		.catch((err) => console.error(`mode-docs: commit threw for ${rel}: ${err.message}`));

	return p;
}

// Bug found building the /find attachment (D-53, carried over here per
// the spec's explicit warning): the thing attached to the thread must be
// the FULL document, not a second rendering of the in-thread summary. The
// summary is for the message; `content` here is always the full document
// text, read back from disk after writeDoc so there's no way for the
// attachment to drift from what's actually stored.
async function attachFullDocument(client, { id, mode, channel, threadTs }) {
	const persona = personaFor(mode);
	const content = readDoc(id, mode);
	if (!content) return { ok: false, reason: "no_document" };
	return uploadThreadFile(client, {
		channel,
		thread_ts: threadTs,
		filename: persona.outputDoc,
		title: persona.outputTitle,
		content,
	});
}

const SUMMARY_PROMPT =
	"Summarise the document below in under 120 words for a Slack message. Do not restate it in full -- " +
	"say what it covers and anything the founder should know before opening it. The full document is " +
	"attached separately.";

async function summarizeForThread(content) {
	const { content: text } = await callFlash(
		[
			{ role: "system", content: SUMMARY_PROMPT },
			{ role: "user", content: content.slice(0, 60000) },
		],
		{ model: MODEL, maxTokens: 600 },
	);
	return text.trim();
}

// Runs one persona turn: builds the feeding-rule prompt (previous
// document + thread context + the founder's message), calls the model,
// and returns either a refusal (see personas.parseRefusal) or the raw
// reply text. Does NOT write the document -- callers decide whether a
// turn's output is meant to update the mode's document (Change 1) or is
// just conversation.
async function runPersonaTurn({ id, mode, threadContext, userText, maxTokens = 4096 }) {
	const persona = personaFor(mode);
	const inputDoc = readInputDoc(id, mode);
	const upstream = Object.values(PERSONAS).find((p) => p.outputDoc === persona.inputDoc);
	const inputTitle = upstream?.outputTitle || persona.inputDoc;
	const parts = [persona.systemPrompt];
	if (inputDoc) {
		parts.push(`--- ${inputTitle} ---\n${inputDoc}`);
	} else if (persona.inputDoc) {
		parts.push(`--- ${inputTitle} ---\n(does not exist yet)`);
	}
	const messages = [
		{ role: "system", content: parts.join("\n\n") },
		{ role: "user", content: threadContext ? `${threadContext}\n\n---\n${userText}` : userText },
	];
	const { content: text, usage, costUsd, cacheHit } = await callFlash(messages, {
		model: MODEL,
		maxTokens,
	});
	const refusal = parseRefusal(text);
	return { text, refusal, usage, costUsd, cacheHit };
}

// Change 3: produce the document itself (not a conversational reply) --
// used both for a normal "founder asked for a draft" turn and for the
// missing-document generate offer, where the mode being generated is the
// *upstream* one (e.g. entering engineering with no product spec offers
// to generate the product spec, using the product persona, not
// engineering's).
async function generateDraft({ id, mode, threadContext, maxTokens = 4096 }) {
	const persona = personaFor(mode);
	const directive =
		`Write the full ${persona.outputTitle} now, as a complete document -- not a question, not a plan to ` +
		"write it later. Base it on everything above (the input document, if any, and the thread). If there is " +
		"truly not enough to go on, use the REFUSAL:/UNBLOCK: contract instead of guessing.";
	const result = await runPersonaTurn({ id, mode, threadContext, userText: directive, maxTokens });
	return result;
}

module.exports = {
	docPath,
	readDoc,
	readInputDoc,
	writeDoc,
	attachFullDocument,
	summarizeForThread,
	runPersonaTurn,
	generateDraft,
};
