"use strict";

// Change 3 (docs/build-prompt-modes.md): missing and stale documents.
//
// "Generate what's missing. Regenerate only what's stale. Always show it
// before it takes effect. Never silently overwrite what the founder
// wrote." This module owns both halves; mode-switch.js calls
// checkMissingInput() on every mode entry, and commands/proto.js (or
// anything invoking a mode against its input) can call checkStale() the
// same way before proceeding.

const { PERSONAS, personaFor } = require("./personas");
const { readDoc, readInputDoc, writeDoc, generateDraft, runPersonaTurn, attachFullDocument, summarizeForThread } = require("./mode-docs");
const { recordGeneration, generationRecord, hashOf } = require("./doc-meta");
const { callFlash } = require("./llm");

const MODEL = "flash-fast";

// Which mode's persona produces a given document filename -- the mode to
// offer switching to / generating from when that document is missing.
function modeThatProduces(docFilename) {
	return Object.values(PERSONAS).find((p) => p.outputDoc === docFilename)?.mode || null;
}

// Returns null if the mode's input document exists (or the mode has no
// input requirement). Otherwise the shape needed to post Change 3's
// missing-document offer.
function checkMissingInput(id, mode) {
	const persona = personaFor(mode);
	if (!persona.inputDoc) return null;
	if (readInputDoc(id, mode)) return null;
	const missingMode = modeThatProduces(persona.inputDoc);
	const missingPersona = missingMode ? personaFor(missingMode) : null;
	return {
		mode,
		missingDoc: persona.inputDoc,
		missingMode,
		missingTitle: missingPersona?.outputTitle || persona.inputDoc,
		missingLabel: missingPersona?.label || null,
	};
}

function missingDocBlocks(id, offer) {
	const text =
		`${personaFor(offer.mode).label === "PM" ? "Product planning" : offer.mode[0].toUpperCase() + offer.mode.slice(1)} ` +
		`normally works from a ${offer.missingTitle.toLowerCase()}. There isn't one.\n` +
		`I can generate a draft from what exists so far, or you can switch to ${offer.missingMode} and write it yourself.`;
	return {
		text,
		blocks: [
			{ type: "section", text: { type: "mrkdwn", text } },
			{
				type: "actions",
				block_id: "missing_doc",
				elements: [
					{ type: "button", action_id: "generate_doc", style: "primary", text: { type: "plain_text", text: "Generate it" }, value: `${id}::${offer.missingMode}` },
					{ type: "button", action_id: `mode_switch_${offer.missingMode}`, text: { type: "plain_text", text: `Switch to ${offer.missingMode}` }, value: `${id}::${offer.missingMode}` },
				],
			},
		],
	};
}

// Runs the generate side of the offer: uses the persona for the MISSING
// document's own mode (not the mode the founder was trying to enter), so
// entering engineering with no product spec generates the product spec
// via the PM persona reading the research base, not an engineering
// shortcut. Writes the doc, records the generation snapshot (Change 3's
// staleness baseline), posts a summary + the full attachment.
async function generateMissingDoc({ id, mode, client, channel, threadTs, threadContext = "" }) {
	const inputBefore = readInputDoc(id, mode); // the missing mode's OWN input, e.g. research-kb.md for product
	const result = await generateDraft({ id, mode, threadContext });
	if (result.refusal) {
		await client.chat
			.postMessage({ channel, thread_ts: threadTs, text: `Couldn't generate a ${personaFor(mode).outputTitle}: ${result.refusal.what}\nUnblock: ${result.refusal.unblock}` })
			.catch(() => {});
		return { ok: false, reason: "refused", refusal: result.refusal };
	}
	writeDoc(id, mode, result.text, { autoGenerated: true });
	recordGeneration(id, mode, inputBefore);
	const summary = await summarizeForThread(result.text).catch(() => result.text.slice(0, 400));
	await client.chat
		.postMessage({ channel, thread_ts: threadTs, text: `⚙️ Auto-generated ${personaFor(mode).outputTitle} (${personaFor(mode).mode} mode):\n\n${summary}` })
		.catch(() => {});
	await attachFullDocument(client, { id, mode, channel, threadTs });
	return { ok: true, mode };
}

const CLASSIFY_PROMPT = [
	"You are comparing an OLD and a NEW version of an upstream document against a DOWNSTREAM document that was",
	"written based on the OLD version. For every substantive difference between OLD and NEW, classify it as one of:",
	"",
	"COSMETIC — wording only, no effect on anything the downstream document assumed or decided.",
	"ADDITIVE — a new requirement or fact that doesn't invalidate any existing downstream decision, just needs coverage.",
	"CONTRADICTORY — the downstream document rests on something that changed; a specific downstream decision no longer holds.",
	"",
	"Output one line per substantive difference, prefixed COSMETIC:, ADDITIVE:, or CONTRADICTORY:, describing the",
	"change and (for ADDITIVE/CONTRADICTORY) which part of the downstream document it affects. If there are no",
	"substantive differences at all, output exactly: NONE",
].join("\n");

function parseClassification(text) {
	const lines = String(text || "").split("\n").map((l) => l.trim()).filter(Boolean);
	const out = { cosmetic: [], additive: [], contradictory: [] };
	for (const line of lines) {
		const m = line.match(/^(COSMETIC|ADDITIVE|CONTRADICTORY):\s*(.*)$/i);
		if (!m) continue;
		out[m[1].toLowerCase()].push(m[2]);
	}
	return out;
}

// Compares the current input document against the snapshot it was last
// generated against. Returns null if there's no baseline to compare
// (never generated / tracked -- checkMissingInput owns "doesn't exist at
// all") or nothing changed. Otherwise the classified diff.
async function checkStale(id, mode) {
	const persona = personaFor(mode);
	if (!persona.inputDoc || !persona.outputDoc) return null;
	const current = readInputDoc(id, mode);
	const downstream = readDoc(id, mode);
	if (!current || !downstream) return null; // missing-doc case, not stale
	const rec = generationRecord(id, mode);
	if (!rec) return null; // no tracked baseline -- nothing to diff against
	if (hashOf(current) === rec.inputHash) return null; // unchanged

	const { content: text } = await callFlash(
		[
			{ role: "system", content: CLASSIFY_PROMPT },
			{
				role: "user",
				content: `--- DOWNSTREAM (${persona.outputTitle}) ---\n${downstream}\n\n--- OLD upstream ---\n${rec.inputSnapshot || "(none)"}\n\n--- NEW upstream ---\n${current}`,
			},
		],
		{ model: MODEL, maxTokens: 2048 },
	);
	if (/^NONE\s*$/i.test(text.trim())) return null;
	const classification = parseClassification(text);
	const isStale = classification.additive.length > 0 || classification.contradictory.length > 0;
	return { stale: isStale, classification, raw: text };
}

function staleDocBlocks(id, mode, report) {
	const persona = personaFor(mode);
	const counts = `${report.classification.contradictory.length} contradictory, ${report.classification.additive.length} additive, ${report.classification.cosmetic.length} cosmetic`;
	const text = `The upstream document changed since this ${persona.outputTitle.toLowerCase()} was written (${counts}).\nI can regenerate just the stale sections and show you the diff, or you can update them yourself.`;
	return {
		text,
		blocks: [
			{ type: "section", text: { type: "mrkdwn", text } },
			{
				type: "actions",
				block_id: "stale_doc",
				elements: [
					{ type: "button", action_id: "regenerate_stale", style: "primary", text: { type: "plain_text", text: "Regenerate stale sections" }, value: `${id}::${mode}` },
					{ type: "button", action_id: "stale_ack", text: { type: "plain_text", text: "I'll do it" }, value: `${id}::${mode}` },
				],
			},
		],
	};
}

// Section-scoped regeneration: the persona is given its own current
// document plus the classified changes and told to touch ONLY the
// sections those changes affect, copying everything else verbatim.
// Never a blind full rewrite -- "never silently overwrite what the
// founder wrote."
async function regenerateStaleSections({ id, mode, client, channel, threadTs }) {
	const persona = personaFor(mode);
	const report = await checkStale(id, mode);
	if (!report || !report.stale) return { ok: false, reason: "not_stale" };
	const current = readDoc(id, mode);
	const newInput = readInputDoc(id, mode);
	const affected = [...report.classification.contradictory, ...report.classification.additive].map((l) => `- ${l}`).join("\n");
	const messages = [
		{
			role: "system",
			content:
				`${persona.systemPrompt}\n\nYou previously wrote the ${persona.outputTitle} below. The upstream document changed. ` +
				"Revise ONLY the sections affected by the changes listed. Copy every other section byte-for-byte, unchanged -- " +
				"do not rephrase, do not reformat, do not touch anything not listed. Return the FULL document, revised sections " +
				"and all.",
		},
		{
			role: "user",
			content: `--- Current ${persona.outputTitle} ---\n${current}\n\n--- Changes to address ---\n${affected}\n\n--- New upstream document ---\n${newInput}`,
		},
	];
	const { content: revised } = await callFlash(messages, { model: MODEL, maxTokens: 8192 });
	writeDoc(id, mode, revised);
	recordGeneration(id, mode, newInput);
	if (client) {
		const summary = await summarizeForThread(revised).catch(() => revised.slice(0, 400));
		await client.chat.postMessage({ channel, thread_ts: threadTs, text: `♻️ Regenerated stale sections of the ${persona.outputTitle}:\n\n${summary}` }).catch(() => {});
		await attachFullDocument(client, { id, mode, channel, threadTs });
	}
	return { ok: true, before: current, after: revised, report };
}

// Writes the CURRENT MODE'S OWN document from the conversation so far.
//
// This was the hole: writeDoc was only ever reached by generateMissingDoc
// (the missing-input offer) and regenerateStaleSections (the stale
// offer), neither of which is on the conversational path. So a founder
// could work with the PM for an hour and `product-spec.md` would never
// exist -- and the spec would then be generated later, on switching to
// engineering, from the research KB alone as if that hour hadn't happened.
//
// Founder-triggered, never automatic, for the same reason profile diffs
// are proposed rather than applied (D-30): the document is the thing
// downstream modes feed on, so an unconsidered half-thought must not be
// able to overwrite a considered spec. Returns a preview the caller shows
// before it takes effect.
// ONE document-writing path in the system.
//
// This used to carry its own prompt: "rewrite it as one coherent
// document incorporating what the conversation settled". doc-sync.js
// carried a different, stricter one for the same file -- a per-section
// UNCHANGED / APPEND / REVISE decision, written specifically because
// handing a model a blank-page rewrite is what makes it silently drop
// facts (proven: a save over a KB wiped a DGFT trade notice, three
// competitor names and the unit economics). Two prompts writing one file,
// with the weaker one on the path a founder actually reaches, is a bug
// waiting for the first long document. So save now IS the sync, invoked
// explicitly rather than by turn count.
//
// Kept as a named export because callers and tests reference it.
async function saveModeDocument({ id, mode, client, channel, threadTs }) {
	const persona = personaFor(mode);
	if (!persona.outputDoc) {
		return { ok: false, reason: `${mode} mode produces no document (proto writes artifacts, audit writes a verdict)` };
	}
	const { syncModeDocument } = require("./doc-sync");
	const res = await syncModeDocument({ id, mode, chatTs: threadTs, client, channel, threadTs, announce: true });
	if (!res.ok) return res;
	if (res.skipped) return { ok: true, mode, skipped: res.skipped, wordCount: null };
	return {
		ok: true, mode, created: !!res.created, wordCount: res.after,
		previousWordCount: res.before, shrankBy: res.shrankBy, materialShrink: res.materialShrink,
		excluded: res.excluded || null,
	};
}

// The save both invocation paths share: `@Mill save`, and the agent's
// `save` tool when a founder asks the persona to write its document.
//
// This existed only inside index.js's app_mention branch, which meant a
// founder saying "create a product spec" -- the plainest possible request
// for this exact operation -- could never reach it. The agent had ten
// tools and none of them wrote a document, so the PM answered in prose
// and the spec appeared later as a side effect of turn-count bookkeeping.
async function runSaveForThread({ id, mode, client, channel, threadTs, progressTs = null }) {
	const result = await saveModeDocument({ id, mode, client, channel, threadTs });
	const text = result.ok
		? result.skipped
			// Honest rather than silent: an explicit save with nothing new
			// to fold in should say so, not imply it rewrote the document.
			? result.skipped === "no session"
				// Reachable from `@Mill save` typed in the channel rather
				// than in a chat thread. "no session" is meaningless to a
				// founder; say which thread it needs.
				? "_I can only save from inside a chat thread — open the chat and ask there._"
				: `_Nothing new to add — ${result.skipped}._`
			: result.excluded
				// The detail is already in the sync's own post; this line
				// just makes sure the founder cannot read "Saved" and miss
				// that something was deliberately left out.
				? `_Saved (${result.wordCount} words) — with part of that request left out; see above._`
				: `_Saved (${result.wordCount} words)._`
		: result.refusal
			? `${result.refusal.what}\nUNBLOCK: ${result.refusal.unblock}`
			: `Couldn't save: ${result.reason}`;
	if (progressTs) await client.chat.update({ channel, ts: progressTs, text }).catch(() => {});
	else await client.chat.postMessage({ channel, thread_ts: threadTs, text }).catch(() => {});
	// The card's Docs line changes the moment a document exists.
	if (threadTs) {
		const { touchAndRepin } = require("./chat-card");
		await touchAndRepin(client, id, threadTs).catch(() => {});
	}
	return { ...result, text };
}

module.exports = {
	runSaveForThread,
	saveModeDocument,
	checkMissingInput,
	missingDocBlocks,
	generateMissingDoc,
	checkStale,
	staleDocBlocks,
	regenerateStaleSections,
	parseClassification,
};
